"use client";
import { useEffect, useMemo, useState } from "react";
import { foods, getFood } from "../data/foods";
import { recipes, scoreRecipe } from "../data/recipes";
import { parseFoodInput, parsedToItem } from "../lib/foodParser";
import { addNutrition, blankNutrition, calculateGoal, fmt, foodNutrition, mealTypeForNow, overage, remaining } from "../lib/nutrition";
import { clearData, initialData, loadData, saveData } from "../lib/storage";
import type { AppData, Food, Meal, MealItem, MealType, NutritionGoal, ParsedFood, Recipe, UserProfile } from "../types";

type View = "today"|"record"|"confirm"|"search"|"custom"|"meal"|"eat"|"recipe"|"trends"|"mine"|"goals"|"data"|"about";
const uid = () => crypto.randomUUID(); const dateKey = (d = new Date()) => d.toLocaleDateString("en-CA"); const dateLabel = (key: string) => new Intl.DateTimeFormat("zh-CN", {month:"long",day:"numeric",weekday:"short"}).format(new Date(`${key}T12:00:00`));
const nav = [{id:"today",i:"⌁",t:"今天"},{id:"record",i:"＋",t:"记录"},{id:"eat",i:"◈",t:"吃什么"},{id:"trends",i:"⌇",t:"趋势"},{id:"mine",i:"◎",t:"我的"}] as const;
const defaultProfile: UserProfile = {sex:"male",age:26,height:178,weight:70,goal:"bulk",activity:"moderate",trainingDays:4,bulkSpeed:"standard",proteinPerKg:1.8,fatPerKg:.8};

export default function App() {
 const [data,setData] = useState<AppData>(initialData); const [ready,setReady] = useState(false); const [view,setView] = useState<View>("today"); const [selectedDate,setSelectedDate] = useState(dateKey()); const [toast,setToast] = useState(""); const [parsed,setParsed] = useState<ParsedFood[]>([]); const [unknown,setUnknown] = useState<string[]>([]); const [selectedMeal,setSelectedMeal] = useState<Meal|null>(null); const [selectedRecipe,setSelectedRecipe] = useState<Recipe|null>(null);
 useEffect(()=>{ loadData().then(d=>{setData(d);setReady(true);}); if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>undefined); },[]);
 useEffect(()=>{ if(ready) saveData(data); },[data,ready]); useEffect(()=>{ if(!toast) return; const t=setTimeout(()=>setToast(""),2200); return()=>clearTimeout(t); },[toast]);
 const goal = data.goal || (data.profile ? calculateGoal(data.profile) : undefined); const day = data.records[selectedDate] || {date:selectedDate,meals:[]}; const eaten=useMemo(()=>addNutrition(...day.meals.map(m=>m.nutrition)),[day]); const gap=goal?remaining(goal,eaten):blankNutrition(); const excess=goal?overage(goal,eaten):blankNutrition();
 const update=(fn:(d:AppData)=>AppData)=>setData(d=>fn(d)); const go=(next:View)=>{setView(next);window.scrollTo({top:0,behavior:"smooth"});};
 const saveProfile=(p:UserProfile)=>{const calculated=calculateGoal(p);setData(d=>({...d,profile:p,goal:calculated}));setToast("增肌目标已建立");go("today")};
 const saveMeal=(items:MealItem[], type:MealType=mealTypeForNow())=>{if(!items.length)return; const meal:Meal={id:uid(),type,time:new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false}),items,nutrition:addNutrition(...items.map(i=>i.nutrition)),createdAt:new Date().toISOString()};update(d=>({...d,records:{...d.records,[selectedDate]:{date:selectedDate,meals:[...(d.records[selectedDate]?.meals||[]),meal]}}}));setToast("已加入今日饮食");go("today")};
 const deleteMeal=(id:string)=>{if(!confirm("删除这条饮食记录？"))return;update(d=>({...d,records:{...d.records,[selectedDate]:{date:selectedDate,meals:(d.records[selectedDate]?.meals||[]).filter(m=>m.id!==id)}}}));setToast("已删除记录");go("today")};
 const parse=(text:string)=>{const result=parseFoodInput(text,data.customFoods);setParsed(result.parsed);setUnknown(result.unknown);go("confirm")};
 const addRecipe=()=>{if(!selectedRecipe)return; const items=selectedRecipe.ingredients.map(ing=>{const food=getFood(ing.foodId,data.customFoods);return food?{id:uid(),foodId:food.id,foodName:food.name,amount:ing.amount,unit:ing.unit,weight:ing.weight,estimated:false,nutrition:foodNutrition(food,ing.weight)}:null}).filter(Boolean) as MealItem[]; saveMeal(items, selectedRecipe.type==="快速加餐"?"加餐":mealTypeForNow());};
 if(!ready)return <main className="app-shell"><div className="loading">正在打开你的本地营养本…</div></main>;
 if(!data.profile)return <Onboarding profile={defaultProfile} onSave={saveProfile}/>;
 const content = view==="today"?<Today goal={goal!} eaten={eaten} gap={gap} excess={excess} day={day} date={selectedDate} setDate={setSelectedDate} onRecord={()=>go("record")} onEat={()=>go("eat")} onMeal={(m)=>{setSelectedMeal(m);go("meal")}}/> : view==="record"?<Record onParse={parse} onSearch={()=>go("search")} foods={[...data.customFoods,...foods]} onQuick={(f)=>saveMeal([{id:uid(),foodId:f.id,foodName:f.name,amount:1,unit:f.servingUnit,weight:f.defaultServingWeight,estimated:true,nutrition:foodNutrition(f,f.defaultServingWeight)}])}/> : view==="confirm"?<Confirm parsed={parsed} unknown={unknown} onChange={setParsed} onSave={(type)=>saveMeal(parsed.map(parsedToItem),type)} onSearch={()=>go("search")}/> : view==="search"?<Search foods={[...data.customFoods,...foods]} onAdd={(food)=>saveMeal([{id:uid(),foodId:food.id,foodName:food.name,amount:1,unit:food.servingUnit,weight:food.defaultServingWeight,estimated:true,nutrition:foodNutrition(food,food.defaultServingWeight)}])} onCustom={()=>go("custom")}/> : view==="custom"?<CustomFood onSave={(food)=>{update(d=>({...d,customFoods:[...d.customFoods,food]}));setToast("已加入个人食物库");go("search")}}/> : view==="meal"&&selectedMeal?<MealDetail meal={selectedMeal} onDelete={()=>deleteMeal(selectedMeal.id)} onCopy={()=>saveMeal(selectedMeal.items,selectedMeal.type)}/> : view==="eat"?<Eat gap={gap} favorites={data.favoriteRecipes} onRecipe={(r)=>{setSelectedRecipe(r);go("recipe")}}/> : view==="recipe"&&selectedRecipe?<RecipeDetail recipe={selectedRecipe} gap={gap} favorite={data.favoriteRecipes.includes(selectedRecipe.id)} onFavorite={()=>update(d=>({...d,favoriteRecipes:d.favoriteRecipes.includes(selectedRecipe.id)?d.favoriteRecipes.filter(x=>x!==selectedRecipe.id):[...d.favoriteRecipes,selectedRecipe.id]}))} onAdd={addRecipe}/> : view==="trends"?<Trends data={data} goal={goal!} onWeight={(weight)=>{update(d=>({...d,profile:d.profile?{...d.profile,weight}:d.profile,weights:[...d.weights.filter(x=>x.date!==dateKey()),{id:uid(),date:dateKey(),weight}]}));setToast("体重已保存")}}/> : view==="mine"?<Mine profile={data.profile} goal={goal!} onGoals={()=>go("goals")} onData={()=>go("data")} onAbout={()=>go("about")}/> : view==="goals"?<Goals goal={goal!} profile={data.profile} onSave={(g)=>{update(d=>({...d,goal:g}));setToast("目标已更新");go("mine")}} onReset={()=>{update(d=>({...d,goal:calculateGoal(d.profile!)}));setToast("已恢复系统推荐")}}/> : view==="data"?<DataPage data={data} onImport={(d)=>{setData(d);setToast("数据已导入")}} onClear={async()=>{if(confirm("确定清除全部本地数据吗？此操作无法撤销。")){await clearData();setData(initialData());location.reload();}}}/> : <About/>;
 return <main className="app-shell">{content}<BottomNav active={view} onGo={go}/>{toast&&<div className="toast">✓ {toast}</div>}</main>
}

function Onboarding({profile,onSave}:{profile:UserProfile,onSave:(p:UserProfile)=>void}){const [p,setP]=useState(profile);const set=(k:keyof UserProfile,v:any)=>setP({...p,[k]:v});return <main className="onboarding"><div className="brand">↑<span>增肌营养助手</span></div><p className="step">建立我的增肌目标 · 约 1 分钟</p><h1>先认识一下你</h1><p className="muted">我们会在本机计算一个容易开始的每日目标。</p><div className="form-grid"><Choice label="性别" value={p.sex} choices={[['male','男'],['female','女']]} onChange={v=>set('sex',v)}/><Input label="年龄" value={p.age} unit="岁" onChange={v=>set('age',v)}/><Input label="身高" value={p.height} unit="cm" onChange={v=>set('height',v)}/><Input label="当前体重" value={p.weight} unit="kg" onChange={v=>set('weight',v)}/></div><label>日常活动量</label><select value={p.activity} onChange={e=>set('activity',e.target.value)}><option value="sedentary">久坐 · 大部分时间坐着</option><option value="light">轻度活动 · 每周运动 1–3 次</option><option value="moderate">中度活动 · 每周运动 3–5 次</option><option value="high">高度活动 · 高频训练或体力活动</option></select><label>每周力量训练次数</label><select value={p.trainingDays} onChange={e=>set('trainingDays',Number(e.target.value))}>{[0,1,2,3,4,5,6,7].map(x=><option key={x}>{x}</option>)}</select><Choice label="增肌速度" value={p.bulkSpeed} choices={[['conservative','保守增肌'],['standard','标准增肌'],['aggressive','积极增肌']]} onChange={v=>set('bulkSpeed',v)}/><button className="primary" onClick={()=>onSave(p)}>生成我的每日目标</button><p className="disclaimer">本工具提供一般性的健身营养记录与估算，不用于疾病诊断或医疗建议。</p></main>}
function Today({goal,eaten,gap,excess,day,date,setDate,onRecord,onEat,onMeal}:any){const tip=gap.protein>25?"今天蛋白质还差比较多，下一餐可以优先补充高蛋白食物。":gap.carbs>60?"蛋白质基本达标，接下来优先补充碳水。":"今天的目标基本完成，可以不用额外加餐。";return <><Header title="今天" sub={dateLabel(date)} action={<input aria-label="选择日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/>}/><section className="progress-card"><div className="section-kicker">今日进度 <span>目标 {goal.calories} kcal</span></div><div className="progress-main"><Ring value={eaten.calories} target={goal.calories}/><div className="macro-list"><Macro label="蛋白质" value={eaten.protein} target={goal.protein}/><Macro label="碳水" value={eaten.carbs} target={goal.carbs}/><Macro label="脂肪" value={eaten.fat} target={goal.fat}/></div></div></section><section className="gap-card"><h2>还差这些就达标了</h2><div className="gap-grid">{([['蛋白质','protein','g'],['碳水','carbs','g'],['脂肪','fat','g'],['热量','calories','kcal']] as const).map(([label,key,unit])=><div key={key}><span>{label}</span><b>{gap[key]===0?"已达标":fmt(gap[key],unit)}</b>{excess[key]>0&&<small>超出 {fmt(excess[key],unit)}</small>}</div>)}</div></section><p className="tip">✦ {tip}</p><button className="primary" onClick={onRecord}>＋ 记录刚刚吃的</button><button className="secondary" onClick={onEat}>根据缺口帮我配一顿</button><section className="meal-section"><h2>今日饮食</h2>{day.meals.length?day.meals.map((m:Meal)=><button className="meal-card" key={m.id} onClick={()=>onMeal(m)}><div><b>{m.type}</b><small>{m.time}</small></div><strong>{m.nutrition.calories} kcal</strong><p>{m.items.map(i=>`${i.amount}${i.unit}${i.foodName}`).join("、")}</p></button>):<Empty text="今天还没有记录饮食" action="记录第一餐" onAction={onRecord}/>}</section></>}
function Record({onParse,onSearch,foods,onQuick}:any){const [text,setText]=useState("");const recent=foods.slice(0,8);return <><Header title="记录饮食" sub="告诉我你刚刚吃了什么"/><label htmlFor="food-text">自然语言输入</label><textarea id="food-text" value={text} onChange={e=>setText(e.target.value)} placeholder="例如：3个鸡蛋、200g米饭、150g鸡胸肉"/><button className="primary" onClick={()=>onParse(text)}>解析饮食</button><button className="secondary" onClick={onSearch}>搜索食物添加</button><section className="quick"><h2>常吃 / 最近吃过</h2><div className="pills">{recent.map((f:Food)=><button key={f.id} onClick={()=>onQuick(f)}>＋ {f.name}</button>)}</div></section></>}
function Confirm({parsed,unknown,onChange,onSave,onSearch}:any){const [type,setType]=useState<MealType>(mealTypeForNow());return <><Header title="确认饮食" sub="保存前可调整份量"/>{parsed.map((p:ParsedFood,index:number)=><div className="edit-food" key={`${p.food.id}${index}`}><div><b>{p.food.name}</b><small>{p.estimated?"估算 · 按常见份量计算，可修改实际重量":"已按重量计算"}</small></div><input aria-label={`${p.food.name}重量`} type="number" value={p.weight} onChange={e=>{const copy=[...parsed];copy[index]={...p,weight:Number(e.target.value),estimated:false};onChange(copy)}}/><span>g</span><button aria-label="删除食物" onClick={()=>onChange(parsed.filter((_:any,i:number)=>i!==index))}>×</button></div>)}{unknown.length>0&&<div className="unknown">暂时没有找到「{unknown.join("、")}」<button onClick={onSearch}>搜索相似食物</button></div>}<label>归类到</label><select value={type} onChange={e=>setType(e.target.value as MealType)}>{["早餐","午餐","晚餐","加餐","训练前","训练后","其他"].map(x=><option key={x}>{x}</option>)}</select><button className="primary" disabled={!parsed.length} onClick={()=>onSave(type)}>保存记录</button></>}
function Search({foods,onAdd,onCustom}:any){const [q,setQ]=useState("");const list=foods.filter((f:Food)=>!q||[f.name,...f.aliases].some(x=>x.toLowerCase().includes(q.toLowerCase()))).slice(0,40);return <><Header title="搜索食物" sub="本地食物库，离线也能用"/><input className="search" autoFocus placeholder="搜索鸡胸、米饭、香蕉…" value={q} onChange={e=>setQ(e.target.value)}/><button className="secondary compact" onClick={onCustom}>＋ 新增自定义食物</button><div className="food-list">{list.map((f:Food)=><div className="food-row" key={f.id}><div><b>{f.name}</b><small>{f.category} · {f.caloriesPer100g} kcal / 100g</small></div><button onClick={()=>onAdd(f)}>添加</button></div>)}</div></>}
function CustomFood({onSave}:any){const [f,setF]=useState({name:"",caloriesPer100g:0,proteinPer100g:0,carbsPer100g:0,fatPer100g:0,defaultServingWeight:100});const set=(k:string,v:any)=>setF({...f,[k]:v});return <><Header title="新增自定义食物" sub="保存后会加入你的个人食物库"/><Input label="食物名称" value={f.name} onChange={v=>set('name',v)} text/><div className="form-grid"><Input label="每100g 热量" value={f.caloriesPer100g} unit="kcal" onChange={v=>set('caloriesPer100g',v)}/><Input label="蛋白质" value={f.proteinPer100g} unit="g" onChange={v=>set('proteinPer100g',v)}/><Input label="碳水" value={f.carbsPer100g} unit="g" onChange={v=>set('carbsPer100g',v)}/><Input label="脂肪" value={f.fatPer100g} unit="g" onChange={v=>set('fatPer100g',v)}/></div><Input label="默认份量" value={f.defaultServingWeight} unit="g" onChange={v=>set('defaultServingWeight',v)}/><button className="primary" disabled={!f.name} onClick={()=>onSave({id:uid(),name:f.name,aliases:[f.name],category:"自定义",servingUnit:"份",...f,custom:true})}>保存食物</button></>}
function MealDetail({meal,onDelete,onCopy}:any){return <><Header title={meal.type} sub={`${meal.time} · ${meal.nutrition.calories} kcal`}/><NutritionSummary n={meal.nutrition}/><div className="detail-list">{meal.items.map((i:MealItem)=><div key={i.id}><span>{i.foodName} {i.amount}{i.unit}{i.estimated&&" · 估算"}</span><b>{i.nutrition.calories} kcal</b></div>)}</div><button className="primary" onClick={onCopy}>复制到今天</button><button className="danger" onClick={onDelete}>删除这条记录</button></>}
function Eat({gap,favorites,onRecipe}:any){const [filter,setFilter]=useState("智能推荐");let list=[...recipes].sort((a,b)=>scoreRecipe(a,gap)-scoreRecipe(b,gap));if(filter!=="智能推荐")list=list.filter(r=>filter==="快速加餐"?r.type==="快速加餐":filter==="正餐"?r.type==="正餐":r.tags.includes(filter));return <><Header title="吃什么" sub="根据今天还差的营养来推荐"/><div className="pills filters">{["智能推荐","高蛋白","高碳水","低脂","快速加餐","正餐"].map(x=><button className={filter===x?"active":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><p className="recommend-note">还差 {fmt(gap.protein)} 蛋白质 · {fmt(gap.carbs)} 碳水</p>{list.map(r=><button className="recipe-card" key={r.id} onClick={()=>onRecipe(r)}><div><b>{r.name}</b><small>{r.tags.join(" · ")} · {r.cookTime} 分钟</small></div><strong>{r.nutrition.calories} kcal</strong><p>蛋白质 {fmt(r.nutrition.protein)}　碳水 {fmt(r.nutrition.carbs)}　脂肪 {fmt(r.nutrition.fat)}</p></button>)}</>}
function RecipeDetail({recipe,gap,favorite,onFavorite,onAdd}:any){const after={calories:Math.max(0,gap.calories-recipe.nutrition.calories),protein:Math.max(0,gap.protein-recipe.nutrition.protein),carbs:Math.max(0,gap.carbs-recipe.nutrition.carbs),fat:Math.max(0,gap.fat-recipe.nutrition.fat)};return <><Header title={recipe.name} sub={`${recipe.cookTime} 分钟 · ${recipe.difficulty}`} action={<button className="icon-button" onClick={onFavorite} aria-label="收藏食谱">{favorite?"★":"☆"}</button>}/><NutritionSummary n={recipe.nutrition}/><section className="ingredients"><h2>食材</h2>{recipe.ingredients.map((i:any,index:number)=><p key={index}>{getFood(i.foodId)?.name} <b>{i.amount}{i.unit}</b></p>)}</section><section className="steps"><h2>简单做法</h2>{recipe.steps.map((s:string,i:number)=><p key={s}><span>{i+1}</span>{s}</p>)}</section><div className="after"><b>吃完这顿后预计还差</b><span>蛋白质 {fmt(after.protein)} · 碳水 {fmt(after.carbs)}</span></div><button className="primary" onClick={onAdd}>加入今日饮食</button></>}
function Trends({data,goal,onWeight}:any){const [weight,setWeight]=useState(data.profile.weight);const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return dateKey(d)});const total=(d:string)=>addNutrition(...(data.records[d]?.meals||[]).map((m:Meal)=>m.nutrition));const average=Math.round(dates.reduce((s,d)=>s+Math.min(1,total(d).protein/goal.protein),0)/7*100);return <><Header title="趋势" sub="最近 7 天"/><section className="trend-card"><h2>热量达标情况</h2><div className="bars">{dates.map(d=>{const n=total(d);return <div key={d}><span style={{height:`${Math.min(100,n.calories/goal.calories*100)}%`}}/><small>{new Date(d).getDate()}</small></div>})}</div></section><section className="trend-card"><h2>蛋白质平均完成率</h2><strong className="big-number">{average}%</strong><p className="muted">再记录几天，就能看到更清晰的变化趋势。</p></section><section className="trend-card"><h2>记录今日体重</h2><div className="inline-input"><input type="number" value={weight} onChange={e=>setWeight(Number(e.target.value))}/><span>kg</span><button onClick={()=>onWeight(weight)}>保存</button></div>{data.weights.length>1&&<p className="muted">最近一次：{data.weights.at(-1).weight} kg</p>}</section></>}
function Mine({profile,goal,onGoals,onData,onAbout}:any){return <><Header title="我的" sub="你的目标保存在当前设备"/><section className="profile-card"><b>{profile.sex==="male"?"男":"女"} · {profile.age}岁 · {profile.height}cm</b><strong>{profile.weight} kg</strong><span>当前体重</span></section><NutritionSummary n={goal}/><div className="setting-list"><button onClick={onGoals}>营养目标 <span>›</span></button><button onClick={onData}>数据管理 <span>›</span></button><button onClick={onAbout}>关于与隐私 <span>›</span></button></div><p className="privacy">你的饮食和身体数据默认只保存在当前设备，不会自动上传。</p></>}
function Goals({goal,profile,onSave,onReset}:any){const [g,setG]=useState<NutritionGoal>(goal);const set=(k:keyof NutritionGoal,v:number)=>setG({...g,[k]:v,isCustom:true});return <><Header title="营养目标" sub="所有目标都可以手动调整"/><div className="form-grid">{([['calories','热量','kcal'],['protein','蛋白质','g'],['carbs','碳水','g'],['fat','脂肪','g']] as const).map(([key,label,unit])=><Input key={key} label={label} value={g[key]} unit={unit} onChange={v=>set(key,v)}/>)}</div><button className="primary" onClick={()=>onSave(g)}>保存目标</button><button className="secondary" onClick={onReset}>恢复系统推荐</button><p className="muted center">推荐依据：{profile.weight} kg 体重、活动量和增肌速度。</p></>}
function DataPage({data,onImport,onClear}:any){const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`增肌营养助手-${dateKey()}.json`;a.click();URL.revokeObjectURL(a.href);};const importData=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{onImport(JSON.parse(String(reader.result)));}catch{alert("文件格式不正确，请选择之前导出的 JSON 文件。");}};reader.readAsText(file);};return <><Header title="数据管理" sub="数据始终优先保存在本机"/><button className="primary" onClick={exportData}>导出数据 JSON</button><label className="file-button">导入数据<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importData(e.target.files[0])}/></label><button className="danger" onClick={onClear}>清除全部数据</button><p className="privacy">导出的文件包含身体信息、饮食、体重和自定义食物。请妥善保管。</p></>}
function About(){return <><Header title="关于与隐私" sub="增肌营养助手 V1"/><section className="about"><h2>本地优先</h2><p>饮食记录、身体数据与食谱收藏只存放在当前浏览器，不会自动上传至服务器。</p><h2>安装到主屏幕</h2><p>iPhone 请在 Safari 的分享菜单中选择“添加到主屏幕”；Android Chrome 可在菜单中选择“安装应用”。安装后，核心记录、搜索、计算和推荐都可离线使用。</p><h2>健康提示</h2><p>本工具提供一般性的健身营养记录与估算信息，不用于疾病诊断或医疗建议。特殊健康状况、孕期、未成年人或有特殊饮食需求时，请咨询专业人士。</p></section></>}
function BottomNav({active,onGo}:any){return <nav className="bottom-nav">{nav.map(x=><button key={x.id} className={active===x.id?"active":""} onClick={()=>onGo(x.id)}><span>{x.i}</span>{x.t}</button>)}</nav>}
function Header({title,sub,action}:{title:string,sub:string,action?:React.ReactNode}){return <header className="header"><div><p>{sub}</p><h1>{title}</h1></div>{action}</header>}
function Ring({value,target}:{value:number,target:number}){const pct=Math.min(100,value/target*100);return <div className="ring" style={{background:`conic-gradient(var(--lime) ${pct}%, #292d2e 0)`}}><div><b>{Math.round(value)}</b><small>已摄入 kcal</small></div></div>}
function Macro({label,value,target}:{label:string,value:number,target:number}){const pct=Math.min(100,value/target*100);return <div className="macro"><div><span>{label}</span><b>{fmt(value)} / {fmt(target)}</b></div><i><em style={{width:`${pct}%`}}/></i></div>}
function NutritionSummary({n}:{n:any}){return <section className="nutrition-summary"><div><b>{Math.round(n.calories)}</b><span>kcal</span></div><div><b>{fmt(n.protein)}</b><span>蛋白质</span></div><div><b>{fmt(n.carbs)}</b><span>碳水</span></div><div><b>{fmt(n.fat)}</b><span>脂肪</span></div></section>}
function Choice({label,value,choices,onChange}:any){return <div className="choice"><label>{label}</label><div>{choices.map(([v,t]:[string,string])=><button type="button" className={value===v?"selected":""} key={v} onClick={()=>onChange(v)}>{t}</button>)}</div></div>}
function Input({label,value,unit,onChange,text=false}:any){return <label className="input-label">{label}<div><input type={text?"text":"number"} value={value} onChange={e=>onChange(text?e.target.value:Number(e.target.value))}/>{unit&&<span>{unit}</span>}</div></label>}
function Empty({text,action,onAction}:any){return <div className="empty"><p>{text}</p><button onClick={onAction}>{action}</button></div>}
